//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.IO.Pipelines.Networking.Tls.Managed {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Strings() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("System.IO.Pipelines.Networking.Tls.Managed.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Error occurred during a cryptographic operation..
        /// </summary>
        public static string Arg_CryptographyException {
            get {
                return ResourceManager.GetString("Arg_CryptographyException", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The OID value was invalid..
        /// </summary>
        public static string Argument_InvalidOidValue {
            get {
                return ResourceManager.GetString("Argument_InvalidOidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Value was invalid..
        /// </summary>
        public static string Argument_InvalidValue {
            get {
                return ResourceManager.GetString("Argument_InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Object contains only the public half of a key pair. A private key must also be provided..
        /// </summary>
        public static string Cryptography_CSP_NoPrivateKey {
            get {
                return ResourceManager.GetString("Cryptography_CSP_NoPrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified curve &apos;{0}&apos; or its parameters are not valid for this platform..
        /// </summary>
        public static string Cryptography_CurveNotSupported {
            get {
                return ResourceManager.GetString("Cryptography_CurveNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The hash algorithm name cannot be null or empty..
        /// </summary>
        public static string Cryptography_HashAlgorithmNameNullOrEmpty {
            get {
                return ResourceManager.GetString("Cryptography_HashAlgorithmNameNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The string contains a character not in the 7 bit ASCII character set..
        /// </summary>
        public static string Cryptography_Invalid_IA5String {
            get {
                return ResourceManager.GetString("Cryptography_Invalid_IA5String", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified DSA parameters are not valid; P, G and Y must be the same length (the key size)..
        /// </summary>
        public static string Cryptography_InvalidDsaParameters_MismatchedPGY {
            get {
                return ResourceManager.GetString("Cryptography_InvalidDsaParameters_MismatchedPGY", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified DSA parameters are not valid; J (if present) must be shorter than P..
        /// </summary>
        public static string Cryptography_InvalidDsaParameters_MismatchedPJ {
            get {
                return ResourceManager.GetString("Cryptography_InvalidDsaParameters_MismatchedPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified DSA parameters are not valid; Q and X (if present) must be the same length..
        /// </summary>
        public static string Cryptography_InvalidDsaParameters_MismatchedQX {
            get {
                return ResourceManager.GetString("Cryptography_InvalidDsaParameters_MismatchedQX", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified DSA parameters are not valid; P, Q, G and Y are all required..
        /// </summary>
        public static string Cryptography_InvalidDsaParameters_MissingFields {
            get {
                return ResourceManager.GetString("Cryptography_InvalidDsaParameters_MissingFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified DSA parameters are not valid; Q&apos;s length must be one of 20, 32 or 64 bytes..
        /// </summary>
        public static string Cryptography_InvalidDsaParameters_QRestriction_LargeKey {
            get {
                return ResourceManager.GetString("Cryptography_InvalidDsaParameters_QRestriction_LargeKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified DSA parameters are not valid; Q must be 20 bytes long for keys shorter than 1024 bits..
        /// </summary>
        public static string Cryptography_InvalidDsaParameters_QRestriction_ShortKey {
            get {
                return ResourceManager.GetString("Cryptography_InvalidDsaParameters_QRestriction_ShortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The specified DSA parameters are not valid; Seed, if present, must be 20 bytes long for keys shorter than 1024 bits..
        /// </summary>
        public static string Cryptography_InvalidDsaParameters_SeedRestriction_ShortKey {
            get {
                return ResourceManager.GetString("Cryptography_InvalidDsaParameters_SeedRestriction_ShortKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Specified key is not a valid size for this algorithm..
        /// </summary>
        public static string Cryptography_InvalidKeySize {
            get {
                return ResourceManager.GetString("Cryptography_InvalidKeySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Specified padding mode is not valid for this algorithm..
        /// </summary>
        public static string Cryptography_InvalidPaddingMode {
            get {
                return ResourceManager.GetString("Cryptography_InvalidPaddingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot open an invalid handle..
        /// </summary>
        public static string Cryptography_OpenInvalidHandle {
            get {
                return ResourceManager.GetString("Cryptography_OpenInvalidHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to &apos;{0}&apos; is not a known hash algorithm..
        /// </summary>
        public static string Cryptography_UnknownHashAlgorithm {
            get {
                return ResourceManager.GetString("Cryptography_UnknownHashAlgorithm", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Cannot use imported EC_KEY. &apos;{0}&apos; is not a supported algorithm..
        /// </summary>
        public static string Cryptography_UnsupportedEcKeyAlgorithm {
            get {
                return ResourceManager.GetString("Cryptography_UnsupportedEcKeyAlgorithm", resourceCulture);
            }
        }
    }
}
